/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Time = IDL.Int;
export const Color = IDL.Variant({ 'black' : IDL.Null, 'white' : IDL.Null });
export const Position = IDL.Record({ 'x' : IDL.Nat, 'y' : IDL.Nat });
export const PieceType = IDL.Variant({
  'king' : IDL.Null,
  'pawn' : IDL.Null,
  'rook' : IDL.Null,
  'queen' : IDL.Null,
  'knight' : IDL.Null,
  'bishop' : IDL.Null,
});
export const Piece = IDL.Record({
  'pieceType' : PieceType,
  'color' : Color,
  'position' : Position,
});
export const GameState = IDL.Record({
  'startTime' : Time,
  'whitePlayer' : IDL.Principal,
  'blackPlayer' : IDL.Principal,
  'winner' : IDL.Opt(Color),
  'enPassantTarget' : IDL.Opt(Position),
  'currentTurn' : Color,
  'board' : IDL.Vec(IDL.Vec(IDL.Opt(Piece))),
});
export const PlayerStats = IDL.Record({
  'gamesPlayed' : IDL.Nat,
  'wins' : IDL.Nat,
  'losses' : IDL.Nat,
  'draws' : IDL.Nat,
  'points' : IDL.Nat,
});
export const AIMatchResult = IDL.Variant({
  'win' : IDL.Null,
  'draw' : IDL.Null,
  'loss' : IDL.Null,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createGame' : IDL.Func([IDL.Text, IDL.Principal], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGameState' : IDL.Func([IDL.Text], [IDL.Opt(GameState)], ['query']),
  'getLeaderboard' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, PlayerStats))],
      ['query'],
    ),
  'getPlayerStats' : IDL.Func([], [PlayerStats], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinGame' : IDL.Func([IDL.Text], [], []),
  'recordAIMatchResult' : IDL.Func([AIMatchResult], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateStats' : IDL.Func(
      [IDL.Opt(IDL.Principal), IDL.Principal, IDL.Principal, IDL.Bool],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Time = IDL.Int;
  const Color = IDL.Variant({ 'black' : IDL.Null, 'white' : IDL.Null });
  const Position = IDL.Record({ 'x' : IDL.Nat, 'y' : IDL.Nat });
  const PieceType = IDL.Variant({
    'king' : IDL.Null,
    'pawn' : IDL.Null,
    'rook' : IDL.Null,
    'queen' : IDL.Null,
    'knight' : IDL.Null,
    'bishop' : IDL.Null,
  });
  const Piece = IDL.Record({
    'pieceType' : PieceType,
    'color' : Color,
    'position' : Position,
  });
  const GameState = IDL.Record({
    'startTime' : Time,
    'whitePlayer' : IDL.Principal,
    'blackPlayer' : IDL.Principal,
    'winner' : IDL.Opt(Color),
    'enPassantTarget' : IDL.Opt(Position),
    'currentTurn' : Color,
    'board' : IDL.Vec(IDL.Vec(IDL.Opt(Piece))),
  });
  const PlayerStats = IDL.Record({
    'gamesPlayed' : IDL.Nat,
    'wins' : IDL.Nat,
    'losses' : IDL.Nat,
    'draws' : IDL.Nat,
    'points' : IDL.Nat,
  });
  const AIMatchResult = IDL.Variant({
    'win' : IDL.Null,
    'draw' : IDL.Null,
    'loss' : IDL.Null,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createGame' : IDL.Func([IDL.Text, IDL.Principal], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGameState' : IDL.Func([IDL.Text], [IDL.Opt(GameState)], ['query']),
    'getLeaderboard' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, PlayerStats))],
        ['query'],
      ),
    'getPlayerStats' : IDL.Func([], [PlayerStats], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinGame' : IDL.Func([IDL.Text], [], []),
    'recordAIMatchResult' : IDL.Func([AIMatchResult], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateStats' : IDL.Func(
        [IDL.Opt(IDL.Principal), IDL.Principal, IDL.Principal, IDL.Bool],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };