/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Color = { 'black' : null } |
  { 'white' : null };
export interface GameState {
  'startTime' : Time,
  'whitePlayer' : Principal,
  'blackPlayer' : Principal,
  'winner' : [] | [Color],
  'currentTurn' : Color,
  'board' : Array<Array<[] | [Piece]>>,
}
export interface Piece {
  'pieceType' : PieceType,
  'color' : Color,
  'position' : Position,
}
export type PieceType = { 'king' : null } |
  { 'pawn' : null } |
  { 'rook' : null } |
  { 'queen' : null } |
  { 'knight' : null } |
  { 'bishop' : null };
export interface PlayerStats {
  'gamesPlayed' : bigint,
  'wins' : bigint,
  'losses' : bigint,
  'draws' : bigint,
  'points' : bigint,
}
export interface Position { 'x' : bigint, 'y' : bigint }
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createGame' : ActorMethod<[string, Principal], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGameState' : ActorMethod<[string], [] | [GameState]>,
  'getLeaderboard' : ActorMethod<[], Array<[Principal, PlayerStats]>>,
  'getPlayerStats' : ActorMethod<[Principal], [] | [PlayerStats]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinGame' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateStats' : ActorMethod<
    [[] | [Principal], Principal, Principal, boolean],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];